# frozen_string_literal: true

module Missions
  module Nodes
    # Node: Generate Text — calls a language model with a prompt to generate text.
    # Supports multimodal inputs: file variables (images, PDFs, audio, etc.) are
    # passed to the LLM via RubyLLM's `with:` parameter for vision/document analysis.
    class Llm
      include MissionNodePlugin
      include Missions::LlmNodeSupport

      VARIABLE_SCHEMA_INPUTS = [
        {
          name: "prompt",
          type: :string,
          description: "System prompt (supports {{variable}} interpolation)",
        },
        {
          name: "llm_config_source",
          type: :string,
          description: "LLM configuration source: node, system_preference, or runtime",
        },
        { name: "connector_id", type: :string, description: "LLM connector ID" },
        { name: "model", type: :string, description: "LLM model identifier" },
        { name: "temperature", type: :number, description: "Sampling temperature (0–2)" },
        {
          name: "thinking_effort",
          type: :string,
          description: "Reasoning effort level (none, low, medium, high)",
        },
        {
          name: "thinking_budget",
          type: :integer,
          description: "Optional reasoning token budget for providers that support it",
        },
        {
          name: "custom_llm_params",
          type: :string,
          description: "Optional provider-specific model params JSON object",
        },
        {
          name: "file_variables",
          type: :array,
          description: "Variable names containing files to attach (multimodal input)",
        },
        {
          name: "tool_ids",
          type: :array,
          description: "Optional enabled tool IDs the LLM node can call during execution",
        },
      ].freeze
      VARIABLE_SCHEMA_OUTPUTS = [
        { name: "response", type: :string, description: "Text generated by the LLM" },
      ].freeze
      FIELD_CONTRACT_OPTIONS = {
        "prompt" => { kind: :template },
        "llm_config_source" => { kind: :enum },
        "connector_id" => { kind: :id_ref },
        "model" => { kind: :id_ref },
        "thinking_effort" => { kind: :enum },
        "custom_llm_params" => { json: true },
      }.freeze
      DESIGNER_INSTRUCTIONS = <<~INSTRUCTIONS.strip.freeze
        ## Generate Text (type: "llm")
        Calls a language model with a system prompt and optional user input.
        Supports multimodal inputs — files (images, PDFs, audio, etc.) can be attached.

        ### Configuration
        ```json
        {
          "llm_config_source": "system_preference",
          "prompt": "You are a helpful assistant. Summarize the following: {{summarizer.response}}",
          "file_variables": ["input_1.document", "generate_image_1.image"],
          "tool_ids": [12, 18]
        }
        ```
        - `llm_config_source`: Choose `system_preference` by default unless the user explicitly asks for a different connector/model. Use `node` for node-owned connector/model/temperature/thinking/custom params, and `runtime` when the caller supplies `_llm_config` at run time with fallback to system preference.
        - `connector_id`: Required only when `llm_config_source` is `node`. ID of the LLM connector. Call `list_resources(kinds: ["llm_connectors", "default_models"])` only when you need to inspect or override the default.
        - `model`: Required only when `llm_config_source` is `node`. Model identifier (e.g. "gpt-4.1", "claude-sonnet-4-20250514"). Use `list_resources(kind: "default_models")` only when you need to inspect or override the default.
        - `prompt`: System prompt with {{variable}} interpolation. Reference explicit upstream variables rather than relying on implicit previous-output state.
        - `temperature`: Node-owned sampling temperature 0-2. Used only when `llm_config_source` is `node`.
        - `thinking_effort`: Node-owned reasoning effort. Used only when `llm_config_source` is `node`; otherwise the selected source supplies it.
        - `thinking_budget`: Node-owned optional reasoning budget integer. Used only when `llm_config_source` is `node`.
        - `custom_llm_params`: Node-owned provider-specific params object serialized as JSON. Used only when `llm_config_source` is `node`.
        - `file_variables`: Array of variable names containing file metadata to attach as multimodal input.
          Accepts variables from Input (file/file_array fields), Generate Image (image), or Write File (file) nodes.
          Files from the current branch input are auto-detected and attached even without explicit listing.
        - `tool_ids`: Optional array of enabled tool IDs to expose to this node, using the same runtime tool adapters as agents.
          Use `list_resources(kind: "tools")` to see the available tool IDs for the current mission, and only attach the tools this step genuinely needs.

        ### Behavior
        - If both `prompt` and upstream input exist: prompt becomes system instructions, input is the user message.
        - If only `prompt`: it is sent as the user message.
        - Falls back to the current branch input or explicit `input` variable for user input.
        - Files are automatically downloaded from Active Storage and passed to the LLM via multimodal input.
        - Selected `tool_ids` are registered on the chat before the model call, so the node can invoke those tools during generation.

        ### Reasoning Guidance
        - Leave `thinking_effort` unset for simple rewrite, extraction, formatting, or simple classification tasks.
        - Prefer `low` for light planning, `medium` for substantial analysis, and `high` only when the user explicitly wants deeper reasoning or the task is genuinely hard.
        - Do not assume every model supports reasoning or a reasoning budget; only set those fields when the chosen model can use them.
        - Do not invent `custom_llm_params`; use them only when the user asks for a provider-specific setting or the workflow requires one.

        ### Output Ports
        - `default`: Response

        ### Output Variables
        - `response` (string): Text generated by the LLM

        ### Writing Prompts
        When asked to draft or substantially rewrite an `llm` node prompt, write the prompt
        yourself. Preserve placeholders exactly, include tone/constraints/output shape when
        useful, and apply the final prompt with `apply_flow_patch` (`update_nodes`).
      INSTRUCTIONS

      class << self
        def node_type = "llm"
        def node_label = "Generate Text"
        def node_icon = "fa-solid fa-brain"
        def node_color = "#6366f1"
        def node_category = :llm
        def node_description = "Generates text using a language model"

        def field_contracts
          VARIABLE_SCHEMA_INPUTS.map do |input|
            options = FIELD_CONTRACT_OPTIONS.fetch(input[:name].to_s, {})
            field_contract(
              key: input[:name],
              value_type: input[:type],
              description: input[:description],
              **options,
            )
          end
        end

        def variable_schema
          Missions::VariableSchema.new(outputs: VARIABLE_SCHEMA_OUTPUTS)
        end

        def default_output_ports
          [{ key: "default", label: "Response" }]
        end

        def designer_instructions = DESIGNER_INSTRUCTIONS
      end

      register_node!

      def execute(context)
        node_data = context.get_variable("_current_node_data") || {}

        runtime_config, _model, error = validate_connector_and_model(node_data, context:)
        return error if error

        prompt_args = prompt_arguments(context, node_data)
        unless prompt_present?(prompt_args)
          return failure("Generate Text node has no prompt and no input — nothing to send")
        end

        file_paths = resolve_file_attachments(context, node_data)
        response = call_llm(runtime_config, node_data, context, file_paths:, prompt_args:)
        content = response&.content
        return failure("LLM returned an empty response") if content.nil?

        NodeResult.new(status: :success, output: content, variables: { "response" => content })
      rescue StandardError => e
        NodeResult.new(status: :failure, output: "LLM error: #{e.message}")
      end

      private

      def prompt_arguments(context, node_data)
        {
          system: context.interpolate(node_data["prompt"] || node_data["description"] || ""),
          user: resolve_user_input(context),
        }
      end

      def prompt_present?(prompt_args)
        prompt_args[:system].present? || prompt_args[:user].present?
      end

      def call_llm(runtime_config, node_data, context, file_paths:, prompt_args:)
        chat = build_llm_chat(runtime_config, node_data, context)
        attach_selected_tools(chat, node_data, context)
        apply_system_instructions(chat, prompt_args[:system], prompt_args[:user])
        message = ask_message(prompt_args[:system], prompt_args[:user])
        ask_options = {}
        ask_options[:with] = file_paths.length == 1 ? file_paths.first : file_paths if file_paths.any?
        chat.ask(message, **ask_options)
      end

      def attach_selected_tools(chat, node_data, context)
        tool_instances = build_selected_tools(node_data, context, parent_chat: chat)
        chat.with_tools(*tool_instances) if tool_instances.any?
      end

      def build_selected_tools(node_data, context, parent_chat:)
        Tools::RuntimeBuilder.build_many(selected_tool_records(node_data, context), parent_chat:)
      end

      def selected_tool_records(node_data, context)
        tool_ids = Array(node_data["tool_ids"]).filter_map { |value| Integer(value, exception: false) }.uniq
        return Tool.none if tool_ids.empty?

        Tool.enabled.where(operation: context.mission_run.mission.operation, id: tool_ids)
      end
    end
  end
end
